"""is_confirmed column was added to User

Revision ID: 3caeba012678
Revises: 968348b7d1e9
Create Date: 2025-06-20 11:01:31.429360

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3caeba012678"
down_revision: Union[str, None] = "968348b7d1e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("users", sa.Column("is_confirmed", sa.Boolean(), nullable=True))

    # Крок 2: встановлюємо значення за замовчуванням для існуючих рядків
    op.execute("UPDATE users SET is_confirmed = FALSE")

    # Крок 3: тепер забороняємо NULL
    op.alter_column("users", "is_confirmed", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_confirmed")
    # ### end Alembic commands ###
